services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"
  django:
    environment:
      redis_host: redis
    build: django_app/
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - redis
  flask:
    environment:
      redis_host: redis
    build: flask_app/
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - redis
